# -*- coding: utf-8 -*-
"""216.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpd4smbBlvAISyvLSDi5MXA9XE8h1Cf5

بسم الله الرحمن الرحيم
الحمد لله الصلوة والسلام على اشرف المخلوقين وعلى آله وصحبه اجمعين امّا بعد
اشهد ان لا اله الّا الله واشهد انّ محمّد رسول الله
"""

# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

!pip -q install openpyxl pingouin scikit-posthocs

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import (
    ttest_ind,
    f_oneway,
    pearsonr,
    levene
)

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan

import pingouin as pg
import scikit_posthocs as sp

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:.4f}")

# ============================================================
# 2. LOAD EXCEL DATA
# ============================================================

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset shape:", df.shape)

print("\nNumber of respondents:", len(df))

print("\nColumn names:")
for i, col in enumerate(df.columns, 1):
    print(i, ":", repr(col))

# ============================================================
# 3. CREATE CLEAN COLUMN NAMES
# ============================================================

original_columns = df.columns.tolist()

clean_columns = [
    f"var_{i+1}"
    for i in range(len(df.columns))
]

column_mapping = pd.DataFrame({
    "Original Column": original_columns,
    "Clean Column": clean_columns
})

df.columns = clean_columns

display(column_mapping)

# ============================================================
# 4. ASSIGN MEANINGFUL VARIABLE NAMES
# ============================================================

new_names = {

    # Screening
    "var_1": "timestamp",
    "var_2": "digital_service_user",

    # Demographics
    "var_3": "gender",
    "var_4": "age",
    "var_5": "education",
    "var_6": "occupation",
    "var_7": "income",
    "var_8": "residence",
    "var_9": "usage_frequency",
    "var_10": "years_using",

    # Cybersecurity Awareness
    "var_11": "C1",
    "var_12": "C2",
    "var_13": "C3",
    "var_14": "C4",
    "var_15": "C5",
    "var_16": "C6",
    "var_17": "C7",
    "var_18": "C8",
    "var_19": "C9",
    "var_20": "C10",

    # Perceived Data Privacy
    "var_21": "D1",
    "var_22": "D2",
    "var_23": "D3",
    "var_24": "D4",
    "var_25": "D5",
    "var_26": "D6",
    "var_27": "D7",

    # System Reliability
    "var_28": "E1",
    "var_29": "E2",
    "var_30": "E3",
    "var_31": "E4",
    "var_32": "E5",
    "var_33": "E6",
    "var_34": "E7",

    # Consumer Trust
    "var_35": "F1",
    "var_36": "F2",
    "var_37": "F3",
    "var_38": "F4",
    "var_39": "F5",
    "var_40": "F6",
    "var_41": "F7",
    "var_42": "F8",
    "var_43": "F9",
    "var_44": "F10"
}

df = df.rename(columns=new_names)

print("New columns:")
print(df.columns.tolist())

# ============================================================
# 5. DATA VERIFICATION
# ============================================================

print("Dataset dimensions:", df.shape)

display(df.head())

print("\nMissing values:")
missing = df.isnull().sum()

display(
    missing[missing > 0]
    .sort_values(ascending=False)
)

# ============================================================
# 6. SCREENING
# ============================================================

print(
    df["digital_service_user"]
    .value_counts(dropna=False)
)

# ============================================================
# STANDARDISE SCREENING VARIABLE
# ============================================================

df["digital_service_user_clean"] = (
    df["digital_service_user"]
    .astype(str)
    .str.strip()
    .str.lower()
)

print(
    df["digital_service_user_clean"]
    .value_counts(dropna=False)
)

# ============================================================
# KEEP VALID DIGITAL SERVICE USERS
# ============================================================

yes_values = [
    "yes",
    "y",
    "1",
    "true"
]

df = df[
    df["digital_service_user_clean"]
    .isin(yes_values)
].copy()

df.reset_index(drop=True, inplace=True)

print(
    "Valid respondents after screening:",
    len(df)
)

# ============================================================
# 7. VARIABLE GROUPS
# ============================================================

demographic_vars = [
    "gender",
    "age",
    "education",
    "occupation",
    "income",
    "residence",
    "usage_frequency",
    "years_using"
]

awareness_items = [
    "C1", "C2", "C3", "C4", "C5",
    "C6", "C7", "C8", "C9", "C10"
]

privacy_items = [
    "D1", "D2", "D3", "D4",
    "D5", "D6", "D7"
]

reliability_items = [
    "E1", "E2", "E3", "E4",
    "E5", "E6", "E7"
]

trust_items = [
    "F1", "F2", "F3", "F4", "F5",
    "F6", "F7", "F8", "F9", "F10"
]

# ============================================================
# CHECK VARIABLES
# ============================================================

required_variables = (
    demographic_vars +
    awareness_items +
    privacy_items +
    reliability_items +
    trust_items
)

missing_variables = [
    x for x in required_variables
    if x not in df.columns
]

if len(missing_variables) == 0:
    print("All required variables are available.")
else:
    print("Missing variables:")
    print(missing_variables)

"""OBJECTIVE 1
Demographic Profile and Levels of the Main Constructs
8. Demographic Frequency and Percentage
"""

# ============================================================
# 8. DEMOGRAPHIC PROFILE
# ============================================================

def frequency_percentage(data, variable):

    frequency = data[variable].value_counts(
        dropna=False
    )

    percentage = (
        data[variable]
        .value_counts(
            normalize=True,
            dropna=False
        ) * 100
    )

    result = pd.DataFrame({
        "Frequency": frequency,
        "Percentage": percentage.round(2)
    })

    return result


for variable in demographic_vars:

    print("\n" + "=" * 70)
    print(variable.upper())
    print("=" * 70)

    display(
        frequency_percentage(
            df,
            variable
        )
    )

# ============================================================
# 9. DEMOGRAPHIC DISTRIBUTION CHARTS
# ============================================================

for variable in demographic_vars:

    plt.figure(figsize=(9, 5))

    order = (
        df[variable]
        .value_counts()
        .index
    )

    sns.countplot(
        data=df,
        x=variable,
        order=order
    )

    plt.title(
        f"Distribution of {variable.replace('_', ' ').title()}"
    )

    plt.xlabel(
        variable.replace("_", " ").title()
    )

    plt.ylabel("Frequency")

    plt.xticks(
        rotation=45,
        ha="right"
    )

    plt.tight_layout()
    plt.show()

"""Cybersecurity Awareness — Objective Scoring


"""

# ============================================================
# 10. CORRECT ANSWERS — CYBERSECURITY AWARENESS
# ============================================================

correct_answers = {

    "C1":
    "T7#mQ9!vL2@p",

    "C2":
    "Avoid the link and contact the bank through its official channel",

    "C3":
    "An urgent request for personal or financial information",

    "C4":
    "To provide an additional layer of identity verification",

    "C5":
    "https://example.com",

    "C6":
    "Install the security update when appropriate",

    "C7":
    "Do not provide the information and verify through an official channel",

    "C8":
    "Avoid sensitive transactions on the unsecured network",

    "C9":
    "Change the password and follow the provider's security procedures",

    "C10":
    "They can help fix security vulnerabilities"
}

# ============================================================
# 11. INSPECT AWARENESS RESPONSES
# ============================================================

for item in awareness_items:

    print("\n" + "=" * 70)
    print(item)
    print("=" * 70)

    display(
        df[item]
        .value_counts(dropna=False)
        .to_frame("Frequency")
    )

# ============================================================
# 12. SCORE CYBERSECURITY AWARENESS
# ============================================================

def score_awareness(series, correct_answer):

    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .eq(
            correct_answer
            .strip()
            .lower()
        )
        .astype(int)
    )


for item in awareness_items:

    df[item + "_score"] = score_awareness(
        df[item],
        correct_answers[item]
    )

# ============================================================
# CHECK AWARENESS SCORING
# ============================================================

awareness_score_columns = [
    item + "_score"
    for item in awareness_items
]

display(
    df[awareness_score_columns]
    .head(10)
)

# ============================================================
# 13. TOTAL CYBERSECURITY AWARENESS SCORE
# ============================================================

df["cybersecurity_awareness"] = (
    df[awareness_score_columns]
    .sum(axis=1)
)

print(
    df["cybersecurity_awareness"]
    .describe()
)

# ============================================================
# 14. AWARENESS SCORE DISTRIBUTION
# ============================================================

awareness_distribution = (
    df["cybersecurity_awareness"]
    .value_counts()
    .sort_index()
    .to_frame("Frequency")
)

awareness_distribution["Percentage"] = (
    awareness_distribution["Frequency"]
    / len(df) * 100
)

display(
    awareness_distribution.round(2)
)

# ============================================================
# 15. LIKERT SCALE CODING
# ============================================================

likert_mapping = {

    "strongly disagree": 1,
    "sd": 1,

    "disagree": 2,
    "d": 2,

    "neutral": 3,
    "n": 3,

    "agree": 4,
    "a": 4,

    "strongly agree": 5,
    "sa": 5
}

likert_items = (
    privacy_items +
    reliability_items +
    trust_items
)

for item in likert_items:

    # Try numerical values first
    numerical = pd.to_numeric(
        df[item],
        errors="coerce"
    )

    # Then try text values
    textual = (
        df[item]
        .astype(str)
        .str.strip()
        .str.lower()
        .map(likert_mapping)
    )

    df[item + "_num"] = (
        numerical
        .fillna(textual)
    )

# ============================================================
# 15. LIKERT SCALE CODING
# ============================================================

likert_mapping = {

    "strongly disagree": 1,
    "sd": 1,

    "disagree": 2,
    "d": 2,

    "neutral": 3,
    "n": 3,

    "agree": 4,
    "a": 4,

    "strongly agree": 5,
    "sa": 5
}

likert_items = (
    privacy_items +
    reliability_items +
    trust_items
)

for item in likert_items:

    # Try numerical values first
    numerical = pd.to_numeric(
        df[item],
        errors="coerce"
    )

    # Then try text values
    textual = (
        df[item]
        .astype(str)
        .str.strip()
        .str.lower()
        .map(likert_mapping)
    )

    df[item + "_num"] = (
        numerical
        .fillna(textual)
    )

# ============================================================
# 16. CHECK LIKERT CODING
# ============================================================

for item in likert_items:

    print(
        item,
        ":",
        sorted(
            df[item + "_num"]
            .dropna()
            .unique()
        )
    )

# ============================================================
# 17. REVERSE CODING
# ============================================================

df["F4_num"] = 6 - df["F4_num"]

df["F6_num"] = 6 - df["F6_num"]

print("F4 and F6 reverse coded successfully.")

# ============================================================
# 18. CREATE CONSTRUCT SCORES
# ============================================================

privacy_num = [
    x + "_num"
    for x in privacy_items
]

reliability_num = [
    x + "_num"
    for x in reliability_items
]

trust_num = [
    x + "_num"
    for x in trust_items
]


df["perceived_data_privacy"] = (
    df[privacy_num]
    .mean(axis=1)
)

df["system_reliability"] = (
    df[reliability_num]
    .mean(axis=1)
)

df["consumer_trust"] = (
    df[trust_num]
    .mean(axis=1)
)

# ============================================================
# 19. OBJECTIVE 1 — DESCRIPTIVE STATISTICS
# ============================================================

main_variables = [
    "cybersecurity_awareness",
    "perceived_data_privacy",
    "system_reliability",
    "consumer_trust"
]

descriptive_statistics = pd.DataFrame({

    "N": df[main_variables].count(),

    "Mean": df[main_variables].mean(),

    "SD": df[main_variables].std(),

    "Minimum": df[main_variables].min(),

    "Maximum": df[main_variables].max(),

    "Skewness": df[main_variables].skew(),

    "Kurtosis": df[main_variables].kurtosis()
})

display(
    descriptive_statistics.round(4)
)

# ============================================================
# 20. CRONBACH'S ALPHA
# ============================================================

alpha_privacy = pg.cronbach_alpha(
    data=df[privacy_num].dropna()
)

alpha_reliability = pg.cronbach_alpha(
    data=df[reliability_num].dropna()
)

alpha_trust = pg.cronbach_alpha(
    data=df[trust_num].dropna()
)

reliability_table = pd.DataFrame({

    "Construct": [
        "Perceived Data Privacy",
        "System Reliability",
        "Consumer Trust"
    ],

    "Number of Items": [
        7,
        7,
        10
    ],

    "Cronbach's Alpha": [
        alpha_privacy[0],
        alpha_reliability[0],
        alpha_trust[0]
    ]
})

display(
    reliability_table.round(4)
)

"""Objective 1 Construct-Level Interpretation Table"""

# ============================================================
# 21. CONSTRUCT SUMMARY
# ============================================================

construct_summary = pd.DataFrame({

    "Construct": [
        "Cybersecurity Awareness",
        "Perceived Data Privacy",
        "System Reliability",
        "Consumer Trust"
    ],

    "Measurement": [
        "Objective score (0–10)",
        "Mean of D1–D7 (1–5)",
        "Mean of E1–E7 (1–5)",
        "Mean of F1–F10 (1–5)"
    ],

    "Mean": [
        df["cybersecurity_awareness"].mean(),
        df["perceived_data_privacy"].mean(),
        df["system_reliability"].mean(),
        df["consumer_trust"].mean()
    ],

    "SD": [
        df["cybersecurity_awareness"].std(),
        df["perceived_data_privacy"].std(),
        df["system_reliability"].std(),
        df["consumer_trust"].std()
    ],

    "Minimum": [
        df["cybersecurity_awareness"].min(),
        df["perceived_data_privacy"].min(),
        df["system_reliability"].min(),
        df["consumer_trust"].min()
    ],

    "Maximum": [
        df["cybersecurity_awareness"].max(),
        df["perceived_data_privacy"].max(),
        df["system_reliability"].max(),
        df["consumer_trust"].max()
    ]
})

display(
    construct_summary.round(4)
)

"""OBJECTIVE 2
Consumer Trust Across Demographic Groups
21. Independent-Samples t-Test

Use this when the demographic variable has exactly two groups
"""

# ============================================================
# 22. INDEPENDENT-SAMPLES T-TEST
# ============================================================

def run_ttest(data, grouping_variable):

    temp = data[
        [
            grouping_variable,
            "consumer_trust"
        ]
    ].dropna()

    groups = temp[
        grouping_variable
    ].unique()

    print("\n" + "=" * 70)
    print(
        f"T-TEST: {grouping_variable}"
    )
    print("=" * 70)

    if len(groups) != 2:

        print(
            "This variable does not have exactly "
            "two groups."
        )

        print(
            "Number of groups:",
            len(groups)
        )

        return None

    group1 = temp.loc[
        temp[grouping_variable] == groups[0],
        "consumer_trust"
    ]

    group2 = temp.loc[
        temp[grouping_variable] == groups[1],
        "consumer_trust"
    ]

    # Welch t-test
    t_stat, p_value = ttest_ind(
        group1,
        group2,
        equal_var=False
    )

    # Levene test
    lev_stat, lev_p = levene(
        group1,
        group2
    )

    result = pd.DataFrame({

        "Group 1": [groups[0]],

        "Group 2": [groups[1]],

        "N Group 1": [len(group1)],

        "N Group 2": [len(group2)],

        "Mean Group 1": [group1.mean()],

        "Mean Group 2": [group2.mean()],

        "t-statistic": [t_stat],

        "p-value": [p_value],

        "Levene p-value": [lev_p]
    })

    display(
        result.round(4)
    )

    return result

gender_ttest = run_ttest(
    df,
    "gender"
)

# ============================================================
# 23. ONE-WAY ANOVA
# ============================================================

def run_anova(data, grouping_variable):

    temp = data[
        [
            grouping_variable,
            "consumer_trust"
        ]
    ].dropna()

    groups = []

    names = []

    for name, group in temp.groupby(
        grouping_variable
    ):

        values = group[
            "consumer_trust"
        ].values

        if len(values) >= 2:

            groups.append(values)
            names.append(name)

    print("\n" + "=" * 70)
    print(
        f"ANOVA: {grouping_variable}"
    )
    print("=" * 70)

    for name, values in zip(
        names,
        groups
    ):

        print(
            f"{name}: "
            f"N={len(values)}, "
            f"Mean={np.mean(values):.4f}, "
            f"SD={np.std(values, ddof=1):.4f}"
        )

    if len(groups) < 2:

        print(
            "Not enough groups for ANOVA."
        )

        return None

    f_stat, p_value = f_oneway(
        *groups
    )

    # Eta squared
    grand_mean = temp[
        "consumer_trust"
    ].mean()

    ss_between = sum(
        len(values)
        * (np.mean(values) - grand_mean) ** 2
        for values in groups
    )

    ss_total = sum(
        (
            temp["consumer_trust"]
            - grand_mean
        ) ** 2
    )

    eta_squared = (
        ss_between / ss_total
    )

    result = pd.DataFrame({

        "Demographic": [
            grouping_variable
        ],

        "F-statistic": [
            f_stat
        ],

        "p-value": [
            p_value
        ],

        "Eta-squared": [
            eta_squared
        ]
    })

    display(
        result.round(4)
    )

    return result

# ============================================================
# 24. ANOVA — ALL DEMOGRAPHIC VARIABLES
# ============================================================

anova_variables = [
    "age",
    "education",
    "occupation",
    "income",
    "residence",
    "usage_frequency",
    "years_using"
]

anova_results = []

for variable in anova_variables:

    result = run_anova(
        df,
        variable
    )

    if result is not None:

        anova_results.append(
            result
        )

anova_summary = pd.concat(
    anova_results,
    ignore_index=True
)

display(
    anova_summary.round(4)
)

# ============================================================
# 25. TUKEY HSD POST-HOC
# ============================================================

def run_tukey(
    data,
    grouping_variable
):

    temp = data[
        [
            grouping_variable,
            "consumer_trust"
        ]
    ].dropna()

    print("\n" + "=" * 70)
    print(
        f"TUKEY HSD: {grouping_variable}"
    )
    print("=" * 70)

    tukey = pg.pairwise_tukey(
        data=temp,
        dv="consumer_trust",
        between=grouping_variable
    )

    display(
        tukey.round(4)
    )

    return tukey

# Example only:
# Run this if the ANOVA for AGE is significant.

tukey_age = run_tukey(
    df,
    "age"
)

# ============================================================
# 26. OBJECTIVE 3 — PEARSON CORRELATION
# ============================================================

correlation_variables = [
    "cybersecurity_awareness",
    "perceived_data_privacy",
    "system_reliability",
    "consumer_trust"
]

correlation_matrix = df[
    correlation_variables
].corr()

display(
    correlation_matrix.round(4)
)

# ============================================================
# 27. CORRELATION WITH P-VALUES
# ============================================================

correlation_results = []

for variable in [
    "cybersecurity_awareness",
    "perceived_data_privacy",
    "system_reliability"
]:

    temp = df[
        [
            variable,
            "consumer_trust"
        ]
    ].dropna()

    r, p = pearsonr(
        temp[variable],
        temp["consumer_trust"]
    )

    correlation_results.append({

        "Variable": variable,

        "Pearson r": r,

        "p-value": p,

        "N": len(temp)
    })

correlation_results = pd.DataFrame(
    correlation_results
)

display(
    correlation_results.round(4)
)

# ============================================================
# 28. CORRELATION HEATMAP
# ============================================================

plt.figure(figsize=(9, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True
)

plt.title(
    "Pearson Correlation Matrix"
)

plt.tight_layout()

plt.show()

# ============================================================
# 29. OBJECTIVE 4 — REGRESSION DATA
# ============================================================

regression_variables = [
    "consumer_trust",
    "cybersecurity_awareness",
    "perceived_data_privacy",
    "system_reliability"
]

reg_df = df[
    regression_variables
].dropna().copy()

print(
    "Regression sample size:",
    len(reg_df)
)

display(
    reg_df.describe().T
)

# ============================================================
# 30. MULTIPLE LINEAR REGRESSION
# ============================================================

X = reg_df[
    [
        "cybersecurity_awareness",
        "perceived_data_privacy",
        "system_reliability"
    ]
]

y = reg_df[
    "consumer_trust"
]

X = sm.add_constant(X)

model = sm.OLS(
    y,
    X
).fit()

print(
    model.summary()
)

# ============================================================
# 31. REGRESSION RESULTS TABLE
# ============================================================

regression_table = pd.DataFrame({

    "Coefficient": model.params,

    "Std. Error": model.bse,

    "t-statistic": model.tvalues,

    "p-value": model.pvalues,

    "CI Lower": model.conf_int()[0],

    "CI Upper": model.conf_int()[1]
})

display(
    regression_table.round(4)
)

# ============================================================
# 32. MODEL FIT
# ============================================================

model_fit = pd.DataFrame({

    "R-squared": [
        model.rsquared
    ],

    "Adjusted R-squared": [
        model.rsquared_adj
    ],

    "F-statistic": [
        model.fvalue
    ],

    "F p-value": [
        model.f_pvalue
    ],

    "N": [
        int(model.nobs)
    ]
})

display(
    model_fit.round(4)
)

from sklearn.preprocessing import StandardScaler

# ============================================================
# 33. STANDARDISED BETA
# ============================================================

predictors = [
    "cybersecurity_awareness",
    "perceived_data_privacy",
    "system_reliability"
]

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_std = scaler_X.fit_transform(
    reg_df[predictors]
)

y_std = scaler_y.fit_transform(
    reg_df[["consumer_trust"]]
).flatten()

X_std = sm.add_constant(
    X_std
)

standardized_model = sm.OLS(
    y_std,
    X_std
).fit()

standardized_results = pd.DataFrame({

    "Variable": [
        "Constant",
        "Cybersecurity Awareness",
        "Perceived Data Privacy",
        "System Reliability"
    ],

    "Standardized Beta":
        standardized_model.params,

    "p-value":
        standardized_model.pvalues
})

display(
    standardized_results.round(4)
)

# ============================================================
# 34. VIF
# ============================================================

X_vif = reg_df[
    predictors
].copy()

X_vif = sm.add_constant(
    X_vif
)

vif_results = pd.DataFrame({

    "Variable": X_vif.columns,

    "VIF": [
        variance_inflation_factor(
            X_vif.values,
            i
        )
        for i in range(
            X_vif.shape[1]
        )
    ]
})

display(
    vif_results.round(4)
)

# ============================================================
# 35. BREUSCH-PAGAN TEST
# ============================================================

bp = het_breuschpagan(
    model.resid,
    model.model.exog
)

bp_results = pd.DataFrame({

    "Test": [
        "LM Statistic",
        "LM p-value",
        "F Statistic",
        "F p-value"
    ],

    "Value": [
        bp[0],
        bp[1],
        bp[2],
        bp[3]
    ]
})

display(
    bp_results.round(4)
)

# ============================================================
# 36. HC3 ROBUST REGRESSION
# ============================================================

robust_model = model.get_robustcov_results(
    cov_type="HC3"
)

print(
    robust_model.summary()
)

# ============================================================
# 37. ROBUST REGRESSION TABLE
# ============================================================

robust_table = pd.DataFrame({

    "Coefficient": robust_model.params,

    "Robust SE": robust_model.bse,

    "t-statistic": robust_model.tvalues,

    "p-value": robust_model.pvalues
})

robust_table.index = [
    "Constant",
    "Cybersecurity Awareness",
    "Perceived Data Privacy",
    "System Reliability"
]

display(
    robust_table.round(4)
)

# ============================================================
# 38. H2-H4 HYPOTHESIS TESTING
# ============================================================

hypothesis_results = pd.DataFrame({

    "Hypothesis": [
        "H2",
        "H3",
        "H4"
    ],

    "Independent Variable": [
        "Cybersecurity Awareness",
        "Perceived Data Privacy",
        "System Reliability"
    ],

    "Coefficient": [
        robust_model.params[1],
        robust_model.params[2],
        robust_model.params[3]
    ],

    "p-value": [
        robust_model.pvalues[1],
        robust_model.pvalues[2],
        robust_model.pvalues[3]
    ]
})

hypothesis_results["Decision"] = np.where(
    hypothesis_results["p-value"] < 0.05,
    "Supported",
    "Not Supported"
)

display(
    hypothesis_results.round(4)
)

# ============================================================
# 39. H1 SUMMARY TABLE
# ============================================================

h1_results = []

# ------------------------------------------------------------
# Gender
# ------------------------------------------------------------

temp = df[
    ["gender", "consumer_trust"]
].dropna()

gender_groups = temp["gender"].unique()

if len(gender_groups) == 2:

    g1 = temp.loc[
        temp["gender"] == gender_groups[0],
        "consumer_trust"
    ]

    g2 = temp.loc[
        temp["gender"] == gender_groups[1],
        "consumer_trust"
    ]

    statistic, p = ttest_ind(
        g1,
        g2,
        equal_var=False
    )

    h1_results.append({

        "Demographic": "Gender",

        "Test": "Independent-samples t-test",

        "Statistic": statistic,

        "p-value": p
    })

else:

    groups = [
        group["consumer_trust"].values
        for _, group in temp.groupby("gender")
    ]

    statistic, p = f_oneway(*groups)

    h1_results.append({

        "Demographic": "Gender",

        "Test": "One-way ANOVA",

        "Statistic": statistic,

        "p-value": p
    })


# ------------------------------------------------------------
# Other demographics
# ------------------------------------------------------------

for variable in anova_variables:

    temp = df[
        [variable, "consumer_trust"]
    ].dropna()

    groups = [
        group["consumer_trust"].values
        for _, group in temp.groupby(variable)
    ]

    if len(groups) >= 2:

        statistic, p = f_oneway(
            *groups
        )

        h1_results.append({

            "Demographic": variable,

            "Test": "One-way ANOVA",

            "Statistic": statistic,

            "p-value": p
        })


h1_summary = pd.DataFrame(
    h1_results
)

h1_summary["Decision"] = np.where(
    h1_summary["p-value"] < 0.05,
    "Significant difference",
    "No significant difference"
)

display(
    h1_summary.round(4)
)

# ============================================================
# 40. EXPORT RESULTS
# ============================================================

output_file = (
    "/content/"
    "Cybersecurity_Consumer_Trust_Analysis.xlsx"
)

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    # Objective 1
    descriptive_statistics.to_excel(
        writer,
        sheet_name="Descriptive Statistics"
    )

    construct_summary.to_excel(
        writer,
        sheet_name="Construct Summary",
        index=False
    )

    reliability_table.to_excel(
        writer,
        sheet_name="Reliability",
        index=False
    )

    # Objective 2
    h1_summary.to_excel(
        writer,
        sheet_name="H1 Demographics",
        index=False
    )

    anova_summary.to_excel(
        writer,
        sheet_name="ANOVA",
        index=False
    )

    # Objective 3
    correlation_matrix.to_excel(
        writer,
        sheet_name="Correlation Matrix"
    )

    correlation_results.to_excel(
        writer,
        sheet_name="Correlation Results",
        index=False
    )

    # Objective 4
    regression_table.to_excel(
        writer,
        sheet_name="Regression"
    )

    robust_table.to_excel(
        writer,
        sheet_name="Robust Regression"
    )

    model_fit.to_excel(
        writer,
        sheet_name="Model Fit",
        index=False
    )

    vif_results.to_excel(
        writer,
        sheet_name="VIF",
        index=False
    )

    hypothesis_results.to_excel(
        writer,
        sheet_name="H2-H4 Hypotheses",
        index=False
    )

print(
    "Analysis results successfully exported."
)

print(
    "File:",
    output_file
)